### ISSUE TITLE
Year labels on x axis

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#102]
Is it possible to include the label for every year that you are plotting data for? For example, in the multi-element, box plot, bar sums,and time series plots only every other year is labelled.  It's picky but would make reviewing data easier, I think.

**Comment by grrmartin-USGS** [comment]
It might get crowded for annual data with more than about 10 years. You
might opt to label every 5-year national compilation, and annually for a
series of up to 11 years (or up to 6 years annually, if 11 labels make it
too crowded.)

**Comment by jshourds-usgs** [comment]
Yeah, that's what I meant-- label every 5 yr compilation.  It just does every ten years now and skips the 5er in between.  Looks a little funny and is hard to read quickly.

**Comment by jshourds-usgs** [comment]
Whoever fixed this-- thanks looks great!!!
