### ISSUE TITLE
Boxplots (notched) that look like rockets and dresses?

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#119]
![bug1](https://cloud.githubusercontent.com/assets/18489683/16154768/4d64e626-347a-11e6-9a2a-a6d1e821e3ac.JPG)

**Comment by jordansread** [comment]
lol'd

**Comment by jshourds-usgs** [comment]
We think this may be a function of using datasets that are too small as per @grrmartin-USGS

**Comment by ldecicco-USGS** [comment]
Yup.
