### ISSUE TITLE
How do I use git?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/wateRuse#12]
Add instructions to readme?

**Comment by jshourds-usgs** [comment]
![20160426_140126](https://cloud.githubusercontent.com/assets/18489683/14832485/2efff8c0-0bc0-11e6-8160-1a6b04b8069c.jpg)

**Comment by dblodgett-usgs** [comment]
Need a clear step by step that illustrates the image attached. A recording or series of screen shots would be helpful.

**Comment by jordansread** [comment]
https://guides.github.com/activities/hello-world/ ?

**Comment by jshourds-usgs** [comment]
[how to set up git and work in R Studio.docx](https://github.com/USGS-R/wateRuse/files/257515/how.to.set.up.git.and.work.in.R.Studio.docx)

Here's a document I came up with in setting up my RStudio back home.  I think this can serve as documentation but might need some editing.

**Comment by dblodgett-usgs** [comment]
Will be written up in #38.
