### ISSUE TITLE
Save data button

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#120]
Download Data button does not seem to be doing anything but opening up the save as box.  Data do not download.

**Comment by ldecicco-USGS** [comment]
Need to check in a browser

**Comment by jshourds-usgs** [comment]
Works like a charm in browser. Thanks for the suggestion @ldecicco-USGS . Probably need to add that instruction into vignette/user manual.  Thanks again.

**Comment by ldecicco-USGS** [comment]
It wouldn't hurt to add a note. But...probably the users are going to open the shiny app with the function `explore_wateRuse`, which by default uses the browser.
