### ISSUE TITLE
Log scale doesn't seem to be working on time series plots

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#122]
Not sure if this is a bug or a function of doing this in the app and not in the browser but I couldn't get the log scale to work.  Thanks for any help/info

**Comment by jshourds-usgs** [comment]
Checked this in browser also. Log scale in both multiple elements and in time series plots does not do a thing.  Can we look into this before sending out to testers?  Thanks.
Going to test the bug report function to see what happens and use this as an issue.  

Update:  too cool!  the bug report button takes you here to issues.  so smart!  :+1:

**Comment by ldecicco-USGS** [comment]
Ha, was just going to ask what the bug report function was...I'll fix this right now.
