### ISSUE TITLE
Download Data button does not save file

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#129]
I've tried several times to use the Download Data button, but the file does not download/save to the folder I specifiy.

**Comment by ldecicco-USGS** [comment]
It will go to where-ever your default "Download" folder is. I think if you want to change that, you need to adjust a setting in Firefox, Chrome, IE, or whatever. Changing that behavior would require a massive programming feat, unless I'm mis-understanding something
