### ISSUE TITLE
Rank data chart does not have shaded bars

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#131]
The shaded bars are not showing up for the RankData charts.  I'm not sure why...
![image](https://cloud.githubusercontent.com/assets/18671567/16590278/ea5b9fd2-42a4-11e6-9298-c2a68da2f600.png)

**Comment by ldecicco-USGS** [comment]
It's fixed on my fork....I'll be pushing it up in a few minutes
