### ISSUE TITLE
Chloropleth map did not show data for all counties AND...

### ISSUE THREAD

**Issue by KatherineSPaybins** [USGS-R/wateRuse#138]
When I tried to add the national data by county dataset downloaded from your site, I got an endless loop in the RStudio window which basically says:
Warning in read_xlsx_(path, sheet, col_names = col_names, col_types = col_types, :+1:  [1495, 17] : expecting numeric: got '--'

**Comment by dblodgett-usgs** [comment]
This issue is partially duplicated by #140.

**Comment by dblodgett-usgs** [comment]
We need to get more specificity about the nature of the county choropleth issue. @jread-usgs will work with @KatherineSPaybins to nail down the issue specifically.

Jen's input:

Think you meant @jshourds.... Just sayin' and trying to save @jread-usgs some confusion and extra work!
