### ISSUE TITLE
Fixed Color Codes in 'Bar Sums' Function in Shiny

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#143]
The color representing each category varies depending on the combination of categories selected to display. The graph could be more readily interpreted  if the color for each category is set/does not vary. For example, using dark green always for the groundwater total (TO.WGWTo ) and blue for the surface water total (TO.WSWTo).  The color scheme used in the 2010 Complication report and the stacked bar chart (Figure 1) work well (below).  

Also, there was mention of the color selection for points in the plots being difficult to distinguish.  Not sure, but a color-blind friendly palette may have been selected (R Graphics Cookbook).

![colors_categories_figure1capture](https://cloud.githubusercontent.com/assets/18426661/18803005/8de987fa-81ba-11e6-8926-6b7f8afed168.JPG)

**Comment by ldecicco-USGS** [comment]
I started this task...but I'll let you guys finish it. Look here:

https://github.com/USGS-R/wateRuse/blob/master/R/barchart_sums.R#L73

Then, find the color you'd prefer here:

http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf

**Comment by jshourds-usgs** [comment]
Thanks to Caryl Wipperfurth-- here are the color matches.  Caryl did the colors for the figures for the national compilation publication:

Total water use=steelblue2
Public supply=mediumpurple4
Irrigation=darkcyan
Aquaculture=steelblue
Mining=darkorange2
Domestic=maroon3
Livestock=firebrick2
Industrial=burlywood4
Thermoelectric=darkgoldenrod2
