### ISSUE TITLE
Enhancements as per Kim Shaffer for next version of wateRuse pkg

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#144]
Compare Two Years Graph Comments:

Bigger Dotes on Choropleth, esp for Texas with 254 counties!

Possible Enhancement:  Allow the Choropleth to be adjustable to allow the user to zoom in and out.  Sometimes, one or two values really skewed the scale.  I would like to zoom in or select a box of data to highlight and investigate further.

Surprisingly, I was able to plot both States at the same time.   but when I clicked on the points, I did not get any of the site information.   If we continue to maintain that more than one State can be on the graph, I would consider color coding dots by States (Shades of Blue for the first State and Shades of green for the second State, etc.).  Also, allow for site information to be displayed with State and County names.

For my review of my data, I am really looking for those outliers.  Currently, I would have to click on each dot to get the State and County information and write this down to verify what County is the outlier.  It would be fantastic if the program did this for me.  Let’s say, I want to know which Counties were 50 percent different between 2010 and 2005, but only values over 1.0 Mgal/d.  It would be great if I could set criteria (50 percent difference and over 1.0 Mgal/d difference) and those counties and there values would be put on the screen and I could download this list with their data. 

When I have more than one State and select the legend, the graph gets really small.

![image](https://cloud.githubusercontent.com/assets/18489683/18960454/cd100efa-8637-11e6-8233-f7e5773c4ea8.png)

Moveability Problem:

When I try to scroll down the left hand side to get to the Counties, change the County code to County name, or even access all the States, the program locks up and I can't scroll down below a State or County.

The first time it happened, I couldn't go farther than 01007.  I got out of the program and it did it again, but this time I couldn't go below NC.  I restarted my computer, and it would let me go below ME this time.  

I noticed that that RStudio was starting the Explore Water Use program in Internet Explorer.  I copied the url and put it in Google Chrome and tried it again.  It also locked up.  At first I could get down to the bottom.  I tried changing the County code to County name, but the program wouldn't change.   Then, once I scrolled back up, it stopped me from go past 39127.

County Name Button Problem:

It is very important to me that I can change the legend to the County Names from the County codes.  I really think that this will be a time saver for everyone.  Sometimes it worked for me and other times it didn’t.

**Comment by jshourds-usgs** [comment]
Compare Two Elements Comments:

Hmmm – I was able to select sites with more than one State being viewed.  But not on Compare Two Years?  So, I revisited and now I can? Not sure what happened there?

Some of my dots were gray/dark brown and hard to see.  I would like to see larger dots and stay away from the gray and dark brown colors.  I also saw a light yellow that I found hard to see. Blue Arrows below in screen shots are to highlight dots that I found difficult to see.  (JLS: Blue Arrows don't show up but I think it's obviously without pointing it out, below)

![image](https://cloud.githubusercontent.com/assets/18489683/18960986/85746d50-8639-11e6-8c28-375189201f33.png)

![image](https://cloud.githubusercontent.com/assets/18489683/18960991/89ce1662-8639-11e6-9525-804a3738e2d8.png)

Graphic heading and units. (This applies to all the different methods to view the data)  I know the units and understand what “PS. GWPop” means, but I have been studying water use for  over 15 years.  I would like to see the graphics be more publication ready so I can put it in a slideshow without having to spend extra time on it.

1)  Add data element and units on the x and y axis (Public Supply Population Served by groundwater, in thousands or Public Supply self-supplied groundwater withdrawals, fresh in Mgal/d). 

2)  Include a heading over the graphic to better explain what I am looking at.  Newer water use people will not know what “PS.WGWFr” is.

**Comment by jshourds-usgs** [comment]
Multi-Elements Comments:

1)  So looking at this, I can see two elements and how they compare over time.  The dots were very small and very difficult to see (yellow and gray). I would suggest a blue and green color that are twice or three times the size of the current dots. 

2)  It be nice if we can select the Counties (or areas we want to see) in the future and have the County and State names on the screen with the codes.

![image](https://cloud.githubusercontent.com/assets/18489683/18961195/305cedb4-863a-11e6-98a7-8aa1d9c530bd.png)

JLS comment: Also in the graphic above, shouldn't the y-axis rescale itself so we can see a finer level of detail or is that too difficult to manage?  I can see where sometimes you would want it and other times you wouldn't but maybe there is a way to manually adjust the scale.  Think this might be related to Kim's earlier comment above about being able to choose a scale, ie a threshold to make outliers pop out.

**Comment by jshourds-usgs** [comment]
Box Plots:

I had a lot of fun playing around in this section.  

1)  I would like to see the screen have the list of the outliers (outside the  50th percentile or a user defined percentile) or have the option to download the outliers.

2)  It would be nice if the user could add color to the box plot to make it “pop” better.

3)  Whenever I use a boxplot, I have an explanation that I use.  It would be nice to have an explanation of the quartiles, outliers, etc on the screen for new people to use and old people to cut and paste into slide shows.

**Comment by jshourds-usgs** [comment]
Time Series:

This was a great opportunity to look at 6 years of data for an element for all the Counties in one or multiple States.  

1)   The points were hard to see.  When I tried to select a point, I got the following error when looking at multiple States.  

![image](https://cloud.githubusercontent.com/assets/18489683/18961440/15758dac-863b-11e6-8389-6d6efd240705.png)

2)  When I choose the legend and toggled off the “Points”, I really like this graphic.  When I tried to select a bar graph to see what site it was, nothing came up.

![image](https://cloud.githubusercontent.com/assets/18489683/18961448/1cb285b6-863b-11e6-9f3d-bde84cff9b09.png)

3) I would like to be able to toggle off and on Counties in the legend.

4) It was hard for me sometimes to differentiate the orange colors and compare County to County.  I would like to be able to make a bar graph with one to multiple counties with the years right next to each other.  May have to use hatching to differentiate year to year.  I can’t really tell in the graphic below how the different “orange” counties compared to each other between 2005 and 2010.

![image](https://cloud.githubusercontent.com/assets/18489683/18961465/268fd9a8-863b-11e6-934c-fa64d73a3d79.png)

**Comment by jshourds-usgs** [comment]
Bar Sums

1)  The color coding on this drove me nuts.  So, the first total I select is always gray (such an ugly color)?  When I select more totals, the colors are constantly changing for each data element? But after selecting multiple totals, if I deselect the first total I selected, all the colors change for the other totals?  This doesn’t make sense.  The Compilation publications have set colors for each of the categories.  I would much prefer to use this color scheme so it is consistent with the compilation.  This way all our graphics are consistent.

**Comment by jshourds-usgs** [comment]
Rank Data

1)  I found this very useful and fun to look at.  I particularly like the use of the blue colors to show the difference between counties.  For some reason, I cannot see the very light blue in the first column on the screen. But when I take a screen shot, I can see it.  I had someone else take a look at this and verified that they can’t see the very light blue either in the “Explore Water Use” program.  Perhaps, make this blue a little darker.

![image](https://cloud.githubusercontent.com/assets/18489683/18961538/54117990-863b-11e6-9895-9a868a4ce346.png)

**Comment by jshourds-usgs** [comment]
Other Items:

When I went into the Report Bugs page and then went back to the Explore Water Use program, none of the graphics would work.

**Comment by ldecicco-USGS** [comment]
@jshourds-usgs could you split up each of these into easily defined "tasks", and create individual issues. Some might be easy for me to just do and close. Others I might want to just give some advise and have one of the other developers take over.

**Comment by jshourds-usgs** [comment]
okay @ldecicco-USGS I split them up.  So going to close this one.
