### ISSUE TITLE
Enhancements to Compare Two Years Graph

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#145]
Compare Two Years Graph Comments:

Bigger Dotes on Choropleth, esp for Texas with 254 counties!

Possible Enhancement: Allow the Choropleth to be adjustable to allow the user to zoom in and out.  I would like to zoom in or select a box of data to highlight and investigate further.

Surprisingly, I was able to plot both States at the same time. but when I clicked on the points, I did not get any of the site information. If we continue to maintain that more than one State can be on the graph, I would consider color coding dots by States (Shades of Blue for the first State and Shades of green for the second State, etc.). Also, allow for site information to be displayed with State and County names.

edit: moved some text to another issue...

When I have more than one State and select the legend, the graph gets really small.

image
![image](https://cloud.githubusercontent.com/assets/18489683/19053214/eb9007e2-8987-11e6-8540-d3bf3ffb8097.png)

Moveability Problem:

When I try to scroll down the left hand side to get to the Counties, change the County code to County name, or even access all the States, the program locks up and I can't scroll down below a State or County.

The first time it happened, I couldn't go farther than 01007. I got out of the program and it did it again, but this time I couldn't go below NC. I restarted my computer, and it would let me go below ME this time.

I noticed that that RStudio was starting the Explore Water Use program in Internet Explorer. I copied the url and put it in Google Chrome and tried it again. It also locked up. At first I could get down to the bottom. I tried changing the County code to County name, but the program wouldn't change. Then, once I scrolled back up, it stopped me from go past 39127.

County Name Button Problem:

It is very important to me that I can change the legend to the County Names from the County codes. I really think that this will be a time saver for everyone. Sometimes it worked for me and other times it didn’t.

**Comment by ldecicco-USGS** [comment]
The legend should scroll now. 

I'm not sure what's happening with the scrolling problem. I always choose 1 state, then minimize that drop-down. Then, I'm able to scroll down all the county or huc's. 

I would not suggest trying to select all states.

**Comment by ldecicco-USGS** [comment]
Could you describe when choosing "county names" did not work? 

otherwise, I think this issue is ready to review @jshourds-usgs

**Comment by jshourds-usgs** [comment]
My scroll was working a little wonky but only when I chose 2 states and one of them was Texas.  It seemed like as long as I just used 1 state and let the program adjust (ie gave it a little time) and minimized the state legend, I was ok.
