### ISSUE TITLE
Enhancements to Compare Two Elements Graph

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#146]
Compare Two Elements:

Hmmm – I was able to select sites with more than one State being viewed. But not on Compare Two Years? So, I revisited and now I can? Not sure what happened there?

Some of my dots were gray/dark brown and hard to see. I would like to see larger dots and stay away from the gray and dark brown colors. I also saw a light yellow that I found hard to see. Blue Arrows below in screen shots are to highlight dots that I found difficult to see. (JLS: Blue Arrows don't show up but I think it's obviously without pointing it out, below)

![image](https://cloud.githubusercontent.com/assets/18489683/19053329/77aee2de-8988-11e6-860b-6833ae6cab7c.png)

![image](https://cloud.githubusercontent.com/assets/18489683/19053335/7edc4a1a-8988-11e6-854f-9bd971d5b141.png)

Graphic heading and units. (This applies to all the different methods to view the data) I know the units and understand what “PS. GWPop” means, but I have been studying water use for over 15 years. I would like to see the graphics be more publication ready so I can put it in a slideshow without having to spend extra time on it.

1) Add data element and units on the x and y axis (Public Supply Population Served by groundwater, in thousands or Public Supply self-supplied groundwater withdrawals, fresh in Mgal/d).

2) Include a heading over the graphic to better explain what I am looking at. Newer water use people will not know what “PS.WGWFr” is.

**Comment by ldecicco-USGS** [comment]
new updates help this issue to I think....but @jshourds-usgs should confirm

**Comment by jshourds-usgs** [comment]
Looks okay except it seems like we lost axis labels.  Kim was asking for words rather than the PS.GWPop but now no axes titles are visible...
