### ISSUE TITLE
Enhancements to Multi-Elements Graph

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#147]
Multi-Elements Comments:

1) So looking at this, I can see two elements and how they compare over time. The dots were very small and very difficult to see (yellow and gray). I would suggest a blue and green color that are twice or three times the size of the current dots.

2) It be nice if we can select the Counties (or areas we want to see) in the future and have the County and State names on the screen with the codes.

![image](https://cloud.githubusercontent.com/assets/18489683/19053436/ede184d4-8988-11e6-9d5f-c029b0be57a6.png)

JLS comment: Also in the graphic above, shouldn't the y-axis rescale itself so we can see a finer level of detail or is that too difficult to manage? I can see where sometimes you would want it and other times you wouldn't but maybe there is a way to manually adjust the scale. Think this might be related to Kim's earlier comment above about being able to choose a scale, ie a threshold to make outliers pop out.

**Comment by ldecicco-USGS** [comment]
@jshourds-usgs have a look and see if it's A-OK.

**Comment by jshourds-usgs** [comment]
Looks good to me.
