### ISSUE TITLE
Enhancements to Box Plots

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#148]
Box Plots:

1) I would like to see the screen have the list of the outliers (outside the 50th percentile or a user defined percentile) or have the option to download the outliers.

2) It would be nice if the user could add color to the box plot to make it “pop” better.

3) Whenever I use a boxplot, I have an explanation that I use. It would be nice to have an explanation of the quartiles, outliers, etc on the screen for new people to use and old people to cut and paste into slide shows.

**Comment by ldecicco-USGS** [comment]
1. you can now hover and see what the outlier are. Not sure if downloading those would be an easy task or not...off-hand I don't know an easy way to do that.
2. like the orange?
3. hmmm....I'll try to dig something up.

**Comment by jshourds-usgs** [comment]
1) Like the hover id but you can't tell where the point is unless you download the data and find it that way.  Is there a way to add the site/county too?  Probably not as there isn't much space.  Just thinking out loud here...

2) Love the orange!  This looks good.  Festive too.

**Comment by rwdudley-usgs** [comment]
How about this for an explanation graphic?
![extended_boxplot_explanation](https://cloud.githubusercontent.com/assets/18488915/19350287/213516fe-9125-11e6-9510-c7ea904f5b84.jpg)

**Comment by rwdudley-usgs** [comment]
Oh I see we've added those cross-whiskers.
![extended_boxplot_explanation](https://cloud.githubusercontent.com/assets/18488915/19352208/f8bb52da-912c-11e6-816f-383aec7b04b0.jpg)
