### ISSUE TITLE
Enhancements to Bar Sums Graph

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#150]
Bar Sums

1) The color coding on this drove me nuts. So, the first total I select is always gray (such an ugly color)? When I select more totals, the colors are constantly changing for each data element? But after selecting multiple totals, if I deselect the first total I selected, all the colors change for the other totals? This doesn’t make sense. The Compilation publications have set colors for each of the categories. I would much prefer to use this color scheme so it is consistent with the compilation. This way all our graphics are consistent.

**Comment by grrmartin-USGS** [comment]
This is the same issue as #143 Fixed Color Codes for Bar Sums Graph
