### ISSUE TITLE
Outlier detection

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/wateRuse#155]
Embedded in another issue:
For my review of my data, I am really looking for those outliers. Currently, I would have to click on each dot to get the State and County information and write this down to verify what County is the outlier. It would be fantastic if the program did this for me. Let’s say, I want to know which Counties were 50 percent different between 2010 and 2005, but only values over 1.0 Mgal/d. It would be great if I could set criteria (50 percent difference and over 1.0 Mgal/d difference) and those counties and there values would be put on the screen and I could download this list with their data.

**Comment by rwdudley-usgs** [comment]
5th time's a charm.

Not sure if I'm handling commits properly. When they failed, I "closed" the commit, made fixes and "force-pushed" the new changes to my fork to amend my previous commit (checking the box "amend previous commit"). 
`git push -f origin master`

Then I would make a "New Pull Request". Repeat until it passed Travis CI, at which point I merged it.
