### ISSUE TITLE
In Plot Two Years-- axis labels

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#159]
X and Y axis labels are cut off.

**Comment by ldecicco-USGS** [comment]
Are you using version 1.0.2? If so, can you put in a screenshot?

**Comment by rwdudley-usgs** [comment]
Doing demo with 1.0.1. Looking at 1.0.2, I see the axis labels look fine.

**Comment by jshourds-usgs** [comment]
So that seems to be another issue I'm having.  I can't update my package to 1.0.2.  Not sure if it's related to my security certificate issue or not...  oh well the demo is over so I can work on fixing that anytime you're free @ldecicco-USGS .  In the meantime, like @grrmartin-USGS , I might just start a new project and see if that works.

**Comment by jshourds-usgs** [comment]
But apparently I can update each package one by one.... At least that's something.  
Could not recreate a new project-- security certificate issues.
