### ISSUE TITLE
More data examples

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/wateRuse#16]
Who uses what files?

General users have: Excel output
Regional users: National dump
National users: National dump
State user: Excel output

**Comment by ldecicco-USGS** [comment]
So, we need data locally to test many conditions.

**Comment by cadieter-usgs** [comment]
I shared three sets of data files through google drive.  They include sets for each of three possible user situations, and different area types (county, huc, aquifer).  I also added readme files for the three main folders.

**Comment by dblodgett-usgs** [comment]
See 'INTERNAL ONLY example data files' google drive folder. Shared with all.
