### ISSUE TITLE
Notch toggle doesn't work on boxplots

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/wateRuse#162]

**Comment by jshourds-usgs** [comment]
Works now in updated version 1.0.2.  Thanks though @rwdudley-usgs

**Comment by rwdudley-usgs** [comment]
Funny, I was using 1.0.2 when I tested this function and noted it wasn't working. Good to hear it actually does work.

**Comment by jshourds-usgs** [comment]
Check and see if it works for you now.  I wonder if it was the HUC dataset that I was using and it wasn't working.  I think I has county loaded at the time.  Now wondering if too much load/traffic on the shiny app could cause it to not work?

**Comment by ldecicco-USGS** [comment]
As long as you are running from RStudio, traffic shouldn't be an issue.

**Comment by grrmartin-USGS** [comment]
Notched Boxes is not working for me--just downloaded 1.0.2 crom cran.

Gary Martin (grmartin@usgs.gov)

Hydrologist

U.S. Geological Survey

Kentucky Water Science Center

9818 Bluegrass Parkway

Louisville, Kentucky

40299-1906

(502) 609-1383 (cell)

(502) 493-1914 (phone)

(502) 493-1909 (fax)

**Comment by ldecicco-USGS** [comment]
I closed this by accident I think. The notched plots won't work with plotly I think. So, if you like the super-easy way to convert ggplot -> interactive plot, you might have to lose the notch feature. I did overlay the actual data, and I think that is more interesting and more intuitive than the notching. Unless I hear otherwise, I'll just remove the shiny app's option to notch.

**Comment by rwdudley-usgs** [comment]
I noticed the data overlay - I have never seen that done before with boxplots - I like it a lot!
I'm fine with losing the notch feature.

**Comment by grrmartin-USGS** [comment]
Yes beautiful boxes and point clouds.  I guess I'll have to live without notches in shiny.  I guess the data can be loaded into the R code for notches.
