### ISSUE TITLE
Hover on Choropleth - reported values have negative signs

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/wateRuse#163]
Values aren't negative, but looks like a negative sign is being appended to the value.

**Comment by rwdudley-usgs** [comment]
I thought I'd take care of this as it seems like it's probably a simple fix, but with the `Plotly` functions, it's not clear to me where/how to do it. Help pointing me in the right direction, @ldecicco-USGS ?

**Comment by ldecicco-USGS** [comment]
I think it's a bug/quirk of plotly. I did just submit something that seems to help though.
