### ISSUE TITLE
https .gov changeover

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/wateRuse#169]
Found these lines with http .gov URLs using https://github.com/wdwatkins/gran_http_gov

HTTPS is supposed be available for everything by the end of December, but may not be yet.

Some of these URLs in .md and other documentation files won't show up on github unless you go to the raw file. Line numbers reference the number in the raw file when opened in a text editor, so the link may not point you to the right spot in some cases if lines are wrapping, etc.

- [x] https://github.com/USGS-R/wateRuse/blob/master/DESCRIPTION#L21
- [x] https://github.com/USGS-R/wateRuse/blob/master/R/wateRuse.R#L15
- [x] https://github.com/USGS-R/wateRuse/blob/master/README.md#L62
- [x] https://github.com/USGS-R/wateRuse/blob/master/inst/shiny/ui.R#L144
- [x] https://github.com/USGS-R/wateRuse/blob/master/man/wateRuse-package.Rd#L16

**Comment by grrmartin-USGS** [comment]
Laura is this something Rob, Jen or I will need to address?

**Comment by ldecicco-USGS** [comment]
It would be a good issue for you guys to fix on your own, once you get the SSH stuff figured out (I think @rwdudley-usgs is good?). All it means is that we have to switch the http to https for our USGS links. This one is pretty easy, some of the other packages it gets more of a mess.
