### ISSUE TITLE
Choropleth hovering labels blank in IE11 

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#173]

**Comment by grrmartin-USGS** [comment]
Blank labels in IE but fine in chrome.

**Comment by jordansread** [comment]
Is full support for IE a target for this tool? I just ask because it usually involves a whole extra chunk of work to deal with the differences in IE. Since it is an internal tool, is it possible to suggest that IE users use a different browser for this instead?

**Comment by rwdudley-usgs** [comment]
Seems reasonable to suggest IE users use a different browser for this. Same is done for other internal tools, for example IPDS.
