### ISSUE TITLE
Clarify R version requirements

### ISSUE THREAD

**Issue by ghost** [USGS-R/wateRuse#180]
The instructions say to install R "version 3.0 or greater" and then get the wateRuse package - but I get this error when using R 3.2.5.

![wateruse not available for all r versions](https://cloud.githubusercontent.com/assets/14081012/23181421/f2d76476-f842-11e6-9dc9-93ee12e8d9f4.JPG)

Please clarify the R version or install requirements in the instructions - I don't know if I need a newer or older version to get this to load, or whether it is a different problem triggering the error.

Thanks.

**Comment by ldecicco-USGS** [comment]
There are installation instructions on hope page of this github repository that add more detail:

https://github.com/USGS-R/wateRuse

Specifically, after installing R, you should paste this into R:

```
rprofile_path = file.path(Sys.getenv("HOME"), ".Rprofile")
write('\noptions(repos=c(getOption(\'repos\'),
  CRAN=\'https://cloud.r-project.org\',
  USGS=\'https://owi.usgs.gov/R\'))\n',
    rprofile_path, 
    append =  TRUE)

cat('Your Rprofile has been updated to include GRAN.
  Please restart R for changes to take effect.')
```

*Restart R*

Then try the `install.packages`. If that doesn't work, paste what R spits out as a response to this Issue. We'll try to figure out what's going on.

**Comment by ghost** [comment]
Thank you, that was the solution and the package was loaded. I had to run Update Packages twice to catch all related updates. 

I would recommend a minor language change to the Step 3 in your instructions - it looked like it was only needed for future automated updates (and I was only going to do a test, not make a long-term commitment). Instead, this step is mandatory.

_Step 3. Add the USGS R repository to your "Rprofile" to get automatic updates. Run the following code:_

Better?

_Step 3. Start R again and paste the following code onto the command line and run it. This will add the USGS R repository to your "Rprofile" to assist with retrieving this USGS package, and to get automatic updates._

You may close this issue - Thank You!
