### ISSUE TITLE
Error with Rank Data tool displaying HUC names from the new-format Export files

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/wateRuse#184]
When using the Rank Data tool for HUC data set, upon choosing `Area.Name` from the area drop down, I get the error:
`ERROR: Duplicate identifiers for rows <rows listed here>`

I have only observed this error with the HUC data set for Indiana. Not sure if this error would occur with other states too - I don't have new-format export files from other states to test with. The tool works fine for county data sets displaying county names imported from the new-format export files.

**Comment by grrmartin-USGS** [comment]
RankData for NJ HUC8 1995 and 2000 seems to work fine.  Must be something with IN data, but I don't see any duplication of HUC8 names as the error seemed to imply. 

![huc8rankdata1capture1](https://cloud.githubusercontent.com/assets/18426661/23570100/b1472ec4-0030-11e7-9658-b70c1d8820a1.JPG)

**Comment by rwdudley-usgs** [comment]
I can't recreate this issue at this time. And given grrmartin also observed NJ HUC08 worked fine. Will close this. Can be reopened if we discover a problem.
