### ISSUE TITLE
Updating shiny to v 1.0.2 seems to have introduced a problem

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/wateRuse#190]
Martha Nielsen updated shiny to version 1.0.2 and found she could no longer load county AWUDs files she could previously load (screen grays and becomes unresponsive).  I tested the same files on my PC with shiny version 1.0.1 and they loaded fine. I updated to shiny version 1.0.2 and now I have the same problem Martha has. Interestingly, the hang up seems to be happening at `observerFunc [...\wateRuse\inst\shiny/server.R#424]` which is the same place things are failing for issue #187 . 
I reached the limits of my abilities to track down that issue for #187. @ldecicco-USGS any thoughts?

**Comment by rwdudley-usgs** [comment]
Here are the files that had issues after the shiny update
[Export-Vermont-County-2010.xlsx](https://github.com/USGS-R/wateRuse/files/937206/Export-Vermont-County-2010.xlsx)
[Export-New-Hampshire-County-2010.xlsx](https://github.com/USGS-R/wateRuse/files/937205/Export-New-Hampshire-County-2010.xlsx)

**Comment by rwdudley-usgs** [comment]
This morning I tested updates @ldecicco-USGS made related to this issue and related to Excel parsing functions.

I found I was able to open most old and new AWUDS files except for these Indiana Aquifer files:
[Export-Indiana-Aquifer-2012b.xlsx](https://github.com/USGS-R/wateRuse/files/954997/Export-Indiana-Aquifer-2012b.xlsx)
[Export-Indiana-Aquifer-2010b.xlsx](https://github.com/USGS-R/wateRuse/files/954998/Export-Indiana-Aquifer-2010b.xlsx)

For files I was able load, most functions worked fine except **Bar Sums** which worked only for the old AWUDS export files for Maine counties (in zip file below) - otherwise for all other files I got `undefined columns selected` error. I confirmed there were data in the files so perhaps there is an issue with the script where totals are computed? I'm out of time this morning to try debugging this.

Here are old and new export files I used for testing:
[new_export_files.zip](https://github.com/USGS-R/wateRuse/files/955108/new_export_files.zip)
[old_export_files.zip](https://github.com/USGS-R/wateRuse/files/955107/old_export_files.zip)

Loading and working with a dump file all checked out fine.

@grrmartin-USGS @jshourds-usgs

**Comment by rwdudley-usgs** [comment]
Clearly it's not working perfectly but I wonder if we could push out a new version (1.0.6.1 or something)? Maybe a better question is _should_ we given the remaining issues? After updating shiny last week, Martha's current version of `wateRuse` has been rendered unuseable and I know she'd like to use it some more.

**Comment by ldecicco-USGS** [comment]
I'm tied up this morning, but I'll have another look this afternoon. I think I found the remaining issue with the files you attached. There were some duplicate rows (I think?), causing a reshape to give out counts instead of values. Either way, I'll push out a new version by the end of the day (either  fixed, or the current version that has the some-what fix)

**Comment by rwdudley-usgs** [comment]
That sounds great. Thank you.

**Comment by rwdudley-usgs** [comment]
Interesting, there is a shiny version 1.0.3 now. https://cran.r-project.org/web/packages/shiny/index.html

**Comment by ldecicco-USGS** [comment]
OK, uploaded the lastest version to GRAN. Start testing, and hopefully we'll get to the bottom of the issues....

The "Update" button *should* do it....

**Comment by rwdudley-usgs** [comment]
Thank you.

**Comment by grrmartin-USGS** [comment]
Updated to wateRuse 1.07 and all packages updated. Loads AWUDS export files
and functions work fine as previously in 1.0.6.  Still has bug will not
load aquifer files unless TP sheet added to workbook (Issue187).  Also,
will not make choropleth when Area=AreaName is set (Issue185).
-Gary





Gary Martin (grmartin@usgs.gov)

Hydrologist



U.S. Geological Survey

Kentucky Water Science Center

9818 Bluegrass Parkway

Louisville, Kentucky

40299-1906



(502) 609-1383 (cell)

(502) 493-1914 (phone)

(502) 493-1909 (fax)

**Comment by grrmartin-USGS** [comment]
What's the purpose of the new 'Stop wateRuse' button?

**Comment by ldecicco-USGS** [comment]
Just an easier way to turn off the app. Click the button and it stops the app *and* stops the app running in the R console.

**Comment by grrmartin-USGS** [comment]
So that will temporarily halt the active code in the event there is a
hang-up? While the Stop button in RStudio terminates the shiny session
completely.  And the 'Reload this page' icon will provide a fresh start
where you can load different data.    (Just want to clarify for the User
Instructions we are writing.)

**Comment by ldecicco-USGS** [comment]
I think if it's hung up, it's hung up. This button will just make it slightly easier to close up the app, because you don't need to click on the Stop button in RStudio.
