### ISSUE TITLE
Lost or hidden 'Download PNG' button

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#198]
On choropleths, 'Download PNG' button gone or hidden:

![lostpngchoroplethcapture](https://user-images.githubusercontent.com/18426661/28221855-01d5df3c-6893-11e7-935e-4a0426c25505.JPG)
![downloadpngchoroplethcapture](https://user-images.githubusercontent.com/18426661/28221872-0fc70e36-6893-11e7-82ee-628c006d7f80.JPG)

**Comment by dblodgett-usgs** [comment]
I'm noticing that there is a download png that works in the bar along the top of the image... does that suffice?

**Comment by grrmartin-USGS** [comment]
Yes, if for choropleth, the state map and screen are scaled so that download png button is visible, that will be fine.  I think the plotly toolbar in some graphs will be fine, if the download buttons in the footer are unavailable.

**Comment by dblodgett-usgs** [comment]
Actually... I think I figured this out. PR to Laura's repo is coming in a later tonight or tomorrow.
