### ISSUE TITLE
Shiny layout/graph scales off

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#200]
Scaling off a bit in version 1.0.8. Graphs encroach on the download buttons and R-code frame in selected plots (Multi-Element and Bar Sums the most, as shown below). Previously, the download buttons and R-code appeared lower on the screen—the download buttons near the ‘Click Here to Switch Areas’ button and the R-code near the ‘Choose Area(s)’ list, as shown at bottom, from figure in the User Instructions.

Loaded dev version of ggplot2 per warning, but graphs appear unchanged.

Warning in origRenderFunc() :
Ignoring explicitly provided widget ID "1f2843b65156d"; Shiny doesn't use them
We recommend that you use the dev version of ggplot2 with ggplotly()
Install it with: devtools::install_github('hadley/ggplot2')

![barsumsoverlapcapture](https://user-images.githubusercontent.com/18426661/29143686-fe12e4f8-7d23-11e7-9651-cba95c617eeb.JPG)
![multielementoverlapcapture](https://user-images.githubusercontent.com/18426661/29143728-2328fb7e-7d24-11e7-8924-61623ca1b22d.JPG)
![originallayoutcapture](https://user-images.githubusercontent.com/18426661/29143735-290b517c-7d24-11e7-9dd3-5b9d72fb5dd4.JPG)

**Comment by dblodgett-usgs** [comment]
What test data are you using? I'm having a hard time identifying what the "development" test data should be. The Bar Sums don't plot with the data in the "excel" folder. I can get them to show up with the data in the "dumps" folder. The inst/extdata/readme.txt says a lot about how these files relate to AWUDS, but it would be very useful to have a README.md (markdown) that describes both how these files relate to AWUDS and how they can be used for testing the app.
