### ISSUE TITLE
Helpful things/links/etc

### ISSUE THREAD

**Issue by jshourds-usgs** [USGS-R/wateRuse#38]
Markdown basics:

http://rmarkdown.rstudio.com/authoring_basics.html

**Comment by dblodgett-usgs** [comment]
Should eventually record these in a wiki or readme documentation.

**Comment by jshourds-usgs** [comment]
http://adv-r.had.co.nz/

This is a cool website Hadley-style for help with R

**Comment by jshourds-usgs** [comment]
From Rob-- a great R coding cheatsheet for ggplot2:

https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

**Comment by dblodgett-usgs** [comment]
Gran - how to install... Lets compile these into the readme and close this issue!

**Comment by dblodgett-usgs** [comment]
@grrmartin-USGS will help review and compile information. @jshourds-usgs will lead.

**Comment by grrmartin-USGS** [comment]
Computer World magazine has an introductory R series.  The part 4 on graphics has some simple examples of using ggplot2. Link:
http://www.computerworld.com/article/2884322/app-development/learn-r-programming-basics-with-our-pdf.html#tk.ctw-infsb

Maybe the pdf (you can register to get it):
http://core0.staticworld.net/assets/2015/02/20/r4beginners_v3.pdf

**Comment by ldecicco-USGS** [comment]
Adding images to github wiki:

https://help.github.com/articles/adding-images-to-wikis/

**Comment by jshourds-usgs** [comment]
![image](https://cloud.githubusercontent.com/assets/18489683/15687646/d4eb029a-2743-11e6-9d40-dafdc68b4614.png)

Cool so this is my workaround.  I'm going to upload pics here using this as my repository and then I can add the link that is created on the wiki.  So don't mind me, nothing to see here....

**Comment by jshourds-usgs** [comment]
https://github.com/jshourds-usgs/Images/issues

Never mind, rather than plug this up and generate emails, I created a new repository.  See link above.  Feel free to use if you want to upload images for wiki pages.

**Comment by ldecicco-USGS** [comment]
You could either put them here:

https://github.com/USGS-R/wateRuse/tree/master/images

Or we could start a new "branch" (that is a more traditional way to do it...but more complicated)

**Comment by ldecicco-USGS** [comment]
Check out the updated Readme:

https://github.com/USGS-R/wateRuse

**Comment by grrmartin-USGS** [comment]
Recommended by Rob: Succinct tutorial.
[Torfs.and.Brauer.Short.R.Intro.pdf](https://github.com/USGS-R/wateRuse/files/295669/Torfs.and.Brauer.Short.R.Intro.pdf)

**Comment by jshourds-usgs** [comment]
@ldecicco-USGS and @grrmartin-USGS 
I am mostly done with the documentation wiki.  I need to do some final cosmetic changes but if either of you want to take a look and make some changes, please feel free!

**Comment by jshourds-usgs** [comment]
@mamaupin-usgs Hi Molly, just wanted to send you the link to the wiki in case it wasn't coming up for you.  Look forward to any changes/suggestions/ideas.  Thanks!

https://github.com/USGS-R/wateRuse/wiki

This particular page being the most important I think:

https://github.com/USGS-R/wateRuse/wiki/1)-Welcome-to-the-wateRuse-help-pages-wiki

**Comment by mamaupin-usgs** [comment]
Thanks, I'm checking it out now.

On Fri, Jun 17, 2016 at 10:06 AM, jshourds-usgs notifications@github.com
wrote:

> @mamaupin-usgs https://github.com/mamaupin-usgs Hi Molly, just wanted
> to send you the link to the wiki in case it wasn't coming up for you. Look
> forward to any changes/suggestions/ideas. Thanks!
> 
> https://github.com/USGS-R/wateRuse/wiki
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-R/wateRuse/issues/38#issuecomment-226810900, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARyLbxsiVYX56CsxhFbz8Rlg82bLOodNks5qMsXxgaJpZM4IR9ey
> .

## 

Molly A. Maupin
Hydrologist
USGS Idaho Water Science Center
230 Collins Road
Boise, ID  83702

Office: (208) 387-1307
Fax:    (208) 387-1372

mamaupin@usgs.gov
