### ISSUE TITLE
Create subset data function for us in multiple plotting functions.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#40]
Should take county/state, water use constituent(s), etc. and return subset of data ready for plotting.

**Comment by ralex-USGS** [comment]
function completed, tested, and submitted in pull request

**Comment by dblodgett-usgs** [comment]
Need to implement in functions that use this functionality. @rwdudley-usgs is on it.

**Comment by dblodgett-usgs** [comment]
@ldecicco-USGS is generalizing and this still needs to get into the timeseries function.
