### ISSUE TITLE
Shiny functionality

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/wateRuse#44]
- [x] DT table in
- [x] download data/plots button working
- [x] Upload data
- [x] clean up options
- [x] implement runApp function
- [x] hover on graphs

**Comment by dblodgett-usgs** [comment]
@ldecicco-USGS This was completed by #63 right?

**Comment by dblodgett-usgs** [comment]
Not sure what I'm doing wrong... I pulled down the latest, built and reloaded, checked, everything looks good. When I run the app, plots just don't show up. Everything appears to be working otherwise.

**Comment by ldecicco-USGS** [comment]
Ha. I suppose you want me to push the version where I don't have the graphs commented out, don't you? It's on it's way, waiting for travis

**Comment by dblodgett-usgs** [comment]
Yes please! 🙅

**Comment by ldecicco-USGS** [comment]
Ohh...travis is checking on R 3.3.0 now, I should probably update

**Comment by ldecicco-USGS** [comment]
Looks like 3.3.0 adds a few new notes that look easy to fix. I'll fix those on a new PR, and merge this one.

**Comment by ldecicco-USGS** [comment]
I'm going to call this done as is written. Mouse hovers on point graphs are pretty straightforward and have been implemented. The hovers on the bar plots (and stacked bars and boxplots) are going to be more complicated. If that is a big priority, we'll need to look into some non-ggplot options.
