### ISSUE TITLE
Add functionality to handle commas in EXPORT dataset filenames

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#45]
The Export files from AWUDS that general users export from AWUDS have commas in the filenames.  Add functionality to accept files that have commas in the filenames.

**Comment by ldecicco-USGS** [comment]
Should be done here:

https://github.com/USGS-R/wateRuse/blob/master/R/getAwudsData.R#L34

So, it's currently renaming the files. I suppose we should re-rename it back to the original commas...but frankly we could just make the rename a "feature" (?)
