### ISSUE TITLE
Add function to calculate "Calculated values" for general user EXPORT files

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#46]
The AWUDS EXPORT files that the general WSC user will be using do not have calculated values (total withdrawals, coefficients, etc.).  

This function would use one of the files from Todd that has the equations for all of the calculated values.  Todd's table may have the data element names with hyphens in them.  These may need to be changed to periods??

**Comment by grrmartin-USGS** [comment]
Not sure what all the calculated values are. But would there be categorical totals that could be readily displayed in a (stacked) bar chart by year?  Just thinking of ways reviewers could quickly spot a problem area - as well as to generate possible report products. Maybe this was mentioned elsewhere...
Here's an example breakdown for categorical and GW/SW for INKY in 2010:  

![inkystackedcapture](https://cloud.githubusercontent.com/assets/18426661/15057462/e6bbc298-12e4-11e6-98ed-ce02c7a5d377.JPG)

**Comment by grrmartin-USGS** [comment]
If the state annual categorical totals will be available, these might be displayed in clustered or stacked bar charts.  Here's the IN data from NWISWeb for the national compilations, for example. 
(First converted from wide to long format.)
#reformat the data to year, category, and value  
categories <- c("PS", "DO", "IN", "TE",  "MI", "LS", "IR", "AQ")
library(tidyr)
test<-gather_(INWU, "TYPE", "VALUE", c(categories), na.rm = FALSE,
              convert = TRUE, factor_key = FALSE)
ggplot(test) + geom_bar(aes_string(x = "YEAR", y = "VALUE", fill = "TYPE"),
            position = "dodge", stat="identity")

ggplot(test) + geom_bar(aes_string(x = "YEAR", y = "VALUE", fill = "TYPE"),
                        position = "stack", stat="identity")

Output:
![in_clustercapture](https://cloud.githubusercontent.com/assets/18426661/15116949/627246e6-15d3-11e6-9b89-6f04d4f3faf7.JPG)

![in_stacked_capture](https://cloud.githubusercontent.com/assets/18426661/15116958/6eac78f0-15d3-11e6-8474-fb77ea4405be.JPG)

**Comment by dblodgett-usgs** [comment]
Will close this issue, but open a new one for the stacked bar chart functionality.
