### ISSUE TITLE
Add Choropleth map function

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#51]
This is one of the major requirements for the package.  This function would allow the user to display chloropleth maps for data elements.

**Comment by dblodgett-usgs** [comment]
Roughed in a little code to create a ggplot2 choropleth. 

```
library(wateRuse)
library(ggplot2)
library(maptools)
nj<-histCounties[which(histCounties@data$STATE_TERR == "New Jersey"),]
njf<-fortify(nj,region = "FIPS")
nj@data$id<-nj@data$FIPS
njf<-merge(njf,nj@data, by="id", all.x=TRUE)
njf<-njf[order(njf$order), ] 
ggplot() + 
  geom_polygon(data = njf,
               aes(x = long, y = lat, group=group, fill=AREA_SQMI), 
               color="black", size=0.25) + coord_map()
```

![rplot](https://cloud.githubusercontent.com/assets/1492803/14898752/19680a36-0d4e-11e6-8f63-319add74602f.png)

**Comment by dblodgett-usgs** [comment]
Switching to DE and adding some WU data. Note commented out scale_fill_distiller.

```
library(wateRuse)
library(ggplot2)
library(maptools)
library(scales)
nj<-histCounties[which(histCounties@data$STATE_TERR == "Delaware"),]
njf<-fortify(nj,region = "FIPS")
nj@data$id<-nj@data$FIPS
njf<-merge(njf,nj@data, by="id", all.x=TRUE)
njf<-njf[order(njf$order), ] 
ggplot() + geom_polygon(data = njf, 
                        aes(x = long, y = lat, group=group, fill=AREA_SQMI), 
                        color="black", size=0.25) + coord_map()

# Lets get some water use data!
w.use.data <- subset_wuse(wUseSample, c("PS.WFrTo","PS.TOPop","STATECOUNTYCODE"), 
                        areas = "DE", area.column = "USSTATEALPHACODE")
names(w.use.data)[names(w.use.data)=="STATECOUNTYCODE"] <- "id"
w.use.data$WFrTo.perCap <- w.use.data$PS.WFrTo/w.use.data$PS.TOPop
njf<-merge(njf,w.use.data, by="id", all.x=TRUE)
ggplot() + geom_polygon(data = njf, 
                        aes(x = long, y = lat, group=group, fill=WFrTo.perCap), 
                        color="black", size=0.25) + coord_map() + 
            scale_fill_gradient(name="Per Capita Freshwater", limits=c(0.1,0.2), low="white", high="red") 
           #scale_fill_distiller(name="Per Capita Freshwater", palette = "YlGn", breaks = pretty_breaks(n = 5))
```

![rplot01](https://cloud.githubusercontent.com/assets/1492803/14900301/8b966542-0d55-11e6-8f78-fb1e9185b37f.png)

**Comment by dblodgett-usgs** [comment]
- [ ] Function 1: Subset polygon data for a particular state(s), particular year, return spatial polygons data frame. Fortify in plot function.
- [ ] Function 2: Data prep for choropleth.  Would take the data element you want to plot, optionally a normalizing element, area type, and area id (state) we are looking at. Return a data.frame suitable for merging with the subset polygons. 
- [ ] Function 3: Hits the first two functions and create a configured plot.

**Comment by ldecicco-USGS** [comment]
Here's another example we could look more into:

```
library("haven")
library("dplyr")
library("stringr")
library("viridisLite")
library("highcharter")
data("uscountygeojson")

url <- "http://www.thearda.com/download/download.aspx?file=U.S.%20Religion%20Census%20Religious%20Congregations%20and%20Membership%20Study,%202010%20(County%20File).SAV"

data <- read_sav(url)

data <- data %>% 
  mutate(CODE = paste("us",
                      tolower(STABBR),
                      str_pad(CNTYCODE, width = 3, pad = "0"),
                      sep = "-"))

n <- 32
dstops <- data.frame(q = 0:n/n, c = substring(viridis(n + 1, option = "B"), 0, 7))
dstops <- list.parse2(dstops)

highchart() %>% 
  hc_title(text = "Total Religious Adherents by County") %>% 
  hc_add_series_map(map = uscountygeojson, df = data,
                    value = "TOTRATE", joinBy = c("code", "CODE"),
                    name = "Adherents", borderWidth = 0.1) %>% 
  hc_colorAxis(stops = dstops, min = 0, max = 1000) %>% 
  hc_legend(layout = "vertical", reversed = TRUE,
            floating = TRUE, align = "right") %>% 
  hc_mapNavigation(enabled = TRUE, align = "right") %>% 
  hc_tooltip(valueDecimals = 0)

```

http://jkunst.com/highcharter/highmaps.html

**Comment by dblodgett-usgs** [comment]
I'd argue to keep things in line with the ggplot/ggmap patterns just to keep things familiar and consistent unless there is a strong argument to go another direction.

**Comment by ldecicco-USGS** [comment]
Is hooked into the shiny app. I don't have a nice automatic way to pick the states, but if you do pick the right state, and there's data, the map pops up.

**Comment by rwdudley-usgs** [comment]
:+1:

**Comment by ldecicco-USGS** [comment]
Is this done?

**Comment by rwdudley-usgs** [comment]
I think we can call it done for now. It works in a basic way and is incorporated into Shiny. Needs to be expanded to include ability to do HUCs and so on. I imagine there might be interest in getting it to do multiple maps to compare years or something. And while it presently can handle a normalizing data element, there is no drop down in Shiny for that yet. I think it is all enhancements we can settle on to get to v 1.0.0.

**Comment by ldecicco-USGS** [comment]
OK, I just added a normalized data element dropdown for that tab. I think we should make a new issue for HUCs. @dblodgett-usgs or someone will probably need to get some huc shapefiles (?)

I'd put multiple maps into another issue too...but maybe wait until it's requested?

**Comment by rwdudley-usgs** [comment]
Sounds great to me. 
Thanks!
