### ISSUE TITLE
Support for multiple 'datasets'

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#54]
Need to be able to two identical region/data elements (datasets) in all our functions/plots. Will also need to espose this functionality in shiny and reports.

**Comment by dblodgett-usgs** [comment]
@cadieter-usgs and @mamaupin-usgs will help with example data and workflow. How do we wire this into the existing shiny functionality.

**Comment by cadieter-usgs** [comment]
@mamaupin-usgs put together a dataset for Arizona, with two sets of data for the same year (2005)(Compilation and Compilation-revised).  We don't want this example dataset on git, so I added a folder to the google drive area with the other dump and example files and put the dataset in google drive.

**Comment by ldecicco-USGS** [comment]
@dblodgett-usgs ...did you have an idea for this?

**Comment by dblodgett-usgs** [comment]
My thinking was to have a convention where the new file would have the year specified like 2005-1 2005-2. Our dataset parsing code would handle whatever convention we decide on and create years of data with the modified year stamp. 

So, what's the easiest convention given how the data is getting exported from AWUDS? And is that realistic given how the current data ingest functions work?

**Comment by ldecicco-USGS** [comment]
It might be easier to rename the 2nd area columns....the map wouldn't work, but the rest of the functions would. Then you could pick "Dane County" and "Dane County_1" and I think all the functions work without modifications. 

Any idea if this is predominantly the Excel files, dump, zip, etc?

**Comment by dblodgett-usgs** [comment]
It seems like some of these would make sense with a second set of areas and others would make sense with a second set of years. 

I think we should get the app to a good state and have users review it and give us a more clear idea of how they would use multiple dataset functions before we try to implement anything.

**Comment by ldecicco-USGS** [comment]
I set this up to add an "a" on supplemental year. Give it a whirl on the app and see if it's what you had in mind.

**Comment by jshourds-usgs** [comment]
So I tried this out and was able to load the AZ zip file and get a 2005 and 2005a on either axis and it's doing what it's supposed to do but I think it may need a few tweaks.  For example, dataset is 
![image](https://cloud.githubusercontent.com/assets/18489683/15724708/55be078c-2816-11e6-9e6c-d59f02fd72fc.png)
And it plots like this: 
![cochise](https://cloud.githubusercontent.com/assets/18489683/15724744/7c52c8f6-2816-11e6-97f3-38ab4df9bbf2.JPG)
So it's plotting correctly but I wonder if there is a way to not repeat the data... It seems like it's plotting 2005 value twice (once on y-axis and once on x-axis) and the same with 2005a value.  Not sure I'm explaining this correctly but I think this might need a little tweaking.  The other plots are similarly confusing.  
In this example I feel like there should be one point for the whole county, like this:
![image](https://cloud.githubusercontent.com/assets/18489683/15725124/5a7b901c-2818-11e6-8ff6-c67d784cab9a.png)
Does that make any sense?  I had to graph in Excel as it would have taken me a whole day to make that graph in R!  :-(

**Comment by ldecicco-USGS** [comment]
How did you load that up? You picked the file "AZ_aq2005_issue54.zip" as the main one and then what as supplemental?

**Comment by jshourds-usgs** [comment]
So maybe that's the issue-- I used the az zip file for both main and supplemental since I saw it had both values for 2005... What should I have used for supplemental?

**Comment by ldecicco-USGS** [comment]
I guess my question is what files do you expect to have to do this sort of analysis? The way I've tested it was to load multiple Excel files (ID and MA), then I took 1 year (1 excel file) and re-jiggered the numbers, that is what I upload in the supplemental. 

But, I don't know the AWUDS workflow. How would you _want_ to do it?

**Comment by mamaupin-usgs** [comment]
Cherl, Are you seeing this string?

I'm also wondering how our workflow from AWUDS would go.  I could see doing
two exports of working datasets, or 1 working dataset and compare to the
best available dataset, then plot an dcompare numbers.  To Laura's
question, the workflow from AWUD would be a series of exports.

What are you thoughts?

Molly
---------- Forwarded message ----------

**Comment by ldecicco-USGS** [comment]
Once you guys figure out your workflow, send me 2 datasets (via email is fine). One that would be the "original" export, and one that is the "working" dataset.
