### ISSUE TITLE
Area Pre-Filter for Shiny and other Applications of a National Dump File

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#64]
Following on a comment in #6. In the case that a national dump file is loaded, we need the ability to work off of a subset of the national dump file. In shiny, this would show up as a pre-filter on USSTATEALPHACODE then the 'Area Column' would be applied to the individual counties, HUCs or aquifers. This will make the Area Column list a reasonable length for the plotting functions and all the rank data function to work with a unique set of areas.

**Comment by ldecicco-USGS** [comment]
Was actually planning to work on this on the plane....So won't be able to have a running pr open until later tonight.
