### ISSUE TITLE
Test calculate_values

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#74]
We need to thoroughly verify and test the calculate_values function. @ldecicco-USGS will describe the issue and pass it off.

**Comment by ldecicco-USGS** [comment]
https://github.com/USGS-R/wateRuse/blob/master/tests/testthat/tests_imports.R#L57

This starts the tests. @jshourds-usgs  can you write a few more tests? Look at the data frame calculation.formula in sysdata.rda . The column "EXPANDEDFORMILA" is what the function is using to create new functions. Find a few that you think are extra important and write a few more tests to make sure the calculations are good.

For the record, there seems to be some calculated columns in the dump file I have. Only the columns that don't exist are created...if that doesn't make sense, let me know.

**Comment by jshourds-usgs** [comment]
So here's what I came up with but I'm not sure it's correct.  It runs and doesn't bomb but it could also not being doing anything...  Was this along the lines of what you were thinking, @ldecicco-USGS ?

```
context("Calculation Tests")

test_that("Calculated Total Population Served", {
  w.use <- wUseSample
  data.elements <- c("PS.TOPop", "PS.SWPop", "PS.GWPop")
  areas <- "10" # NA uses all areas
  area.column <- "STATECODE"
  w.use.sub <- subset_wuse(w.use, data.elements, area.column, areas)

  expect_true(w.use,sum("PS.SWPop" + "PS.GWPop"), "PS.TOPop")
})
```

**Comment by ldecicco-USGS** [comment]
There's a chunk in the "tests_imports.R" file that looks like this:

```
test_that("Test calculations", {

  awuds <- wUseSample
  awuds.calc <- calculate_values(awuds)

  x1 <- awuds.calc$LV.WGWFr
  y1 <- awuds$LS.WGWFr + awuds$LA.WGWFr

  expect_equal(object = x1, expected = y1)

})
```

What it is saying is that the sum of the columns LS.WGWFr and LA.WGWFr equal the column LV.WGWFr.

First...I realized I spelled calculate wrong in the package...I'm doing a pull request now to fix that.

So, for the test you are trying to write, I think it would be:

```
w.use <- wUseSample
data.elements <- c("PS.TOPop", "PS.SWPop", "PS.GWPop")
areas <- "10" # NA uses all areas
area.column <- "STATECODE"
w.use.sub <- subset_wuse(w.use, data.elements, area.column, areas)

w.use.calc <- calculate_values(w.use.sub)

expect_equal((w.use.calc$PS.SWPop + w.use.calc$PS.GWPop), w.use.calc$PS.TOPop)

```

_BUT_ PS.TPPop is not actually calculated from the `calculate_values` function because the PS.TPPop is already populated in the original wUseSample dataset.

**Comment by jshourds-usgs** [comment]
Ah thanks for that code.  That makes sense.

So how can I tell what calculations R is doing and what calcs does awuds do?  From the sysdata.rda calculation formula expanded formula column-- are these all calculations that R is performing? PS-ToPop is there as PS-GWPop + PS-SWPop even though that is a calc that awuds performs? Or is this column showing all the calculations that AWUDS does?

**Comment by ldecicco-USGS** [comment]
Well, the way the code is doing:
1. gets some water use file ie. wUseSample. Let's call this w.use
2. looks at the `calculation.formula` dataframe in sysdata.rda
3. Looks to see what columns are not in the w.use dataframe that are in `calculation.formula$CALCULATION`
4. Creates _those_ new columns based on `calculation.formula$EXPANDEDFORMULA`

...does that make sense? So you could do this:

```
w.use <- wUseSample
w.use.calc <- calculate_values(w.use)

names(w.use.calc)[!(names(w.use.calc) %in% names(w.use))]
```

To get the names of the columns that were created from the `calculate_values` function
