### ISSUE TITLE
Reverse shading scale on choropleth maps

### ISSUE THREAD

**Issue by cadieter-usgs** [USGS-R/wateRuse#78]
Currently on the choropleth maps, the darker colors indicate smaller values and the lighter colors indicate larger values.  We generally have the opposite shading on maps for the national program.  Please **reverse the shading so that lighter colors indicate smaller values, and dark colors indicate larger values.**

**Comment by cadieter-usgs** [comment]
I did a search and maybe **trans = "reverse"** needs to be added to the code
`scale_fill_distiller(name=p.elem, palette = "YlGn", breaks = pretty_breaks(n = 5))
`
I tried adding the code in R-studio and running the revised code, but I can't get the choropleth to show up (with or without the added code).  I wouldn't mind making the update if someone can help walk me through the steps...and help me get the plot to generate.

**Comment by ldecicco-USGS** [comment]
After you add the code in the "choropleth_plot.R" file, try clicking on the "Build & Reload" button in the upper right Build tab. After that, try pasting this in the Console (lower left window in RStudio):

```
w.use <- wUseSample
data.elements <- "PS.WFrTo"
norm.element <- "PS.TOPop"
year <- 2010 
areas <- "Delaware" 
area.column <- "STATE_TERR"
ch.plot <- choropleth_plot(w.use, data.elements, year, areas, area.column, norm.element)
ch.plot

```

If the graph looks the way you want it, push it up to your fork and do a "Pull Request"...

If any of those steps are confusing or give you errors, let me know.

**Comment by grrmartin-USGS** [comment]
Is there a way in Shiny to make a 'loop' that would display the choropleth maps sequentially, in a time-lapse visual?

**Comment by ldecicco-USGS** [comment]
:+1: 

I'm closing the issue because @cadieter-usgs fixed it...but @grrmartin-USGS ...you could create a new issue if you wanted to explore the time-lapse.

**Comment by cadieter-usgs** [comment]
thanks @ldecicco-USGS !   With your notes, I was able to get it to work, reversed the color scale and submitted the Pull Request.  
![image](https://cloud.githubusercontent.com/assets/18671567/15217389/5dedbc6a-1829-11e6-8133-564b6dd73303.png)
