### ISSUE TITLE
Setup hosted shiny for testing

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#94]

**Comment by ldecicco-USGS** [comment]
The link is here:

[https://waterdatascience.shinyapps.io/wateRuse/](https://waterdatascience.shinyapps.io/wateRuse/)

Email me to add users

**Comment by jshourds-usgs** [comment]
@grrmartin-USGS This email, Gary.  I never got the one during the call directly from shinyio.
