### ISSUE TITLE
Vignette Structure and Basic Setup and Descriptions

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#95]
Get the basics of a vignette setup showing how to use the individual functions / plots. @rwdudley-usgs will take a first pass, @grrmartin-USGS will take a second pass, @cadieter-usgs will put in explanatory text and @mamaupin-usgs will do final review.

**Comment by rwdudley-usgs** [comment]
@grrmartin-USGS I have taken a first pass at the vignette document `wateRuse.Rmd`. There is now a section for each function and several examples for each (except the rank data function). I added some basic descriptions.

**Comment by grrmartin-USGS** [comment]
I edit wateRuse.Rmd, then send a git pull request, the same way I would
push code in a git pull request?

(Maybe a procedure to add to documentation?)

**Comment by rwdudley-usgs** [comment]
Yes, except I noticed when I did a push of `wateRuse.Rmd` it seemed I couldn't make a pull request - as if it automatically updated to the master without making a pull request? Perhaps you can shed some light on what happened @ldecicco-USGS?

**Comment by grrmartin-USGS** [comment]
What I have on my PC is an older version I think. It only has these
functions: ### Compare two years

### Compare two elements

### Ranked data element tables

### Time series plots

So it appears what I am git pulling has not been updated with your most
recent changes.

**Comment by ldecicco-USGS** [comment]
@grrmartin-USGS you need to do an "git pull upstream master", then "git push" (which pushes to your fork)

**Comment by ldecicco-USGS** [comment]
@rwdudley-usgs ...were you maybe trying to do a pull request from the USGS-R organization instead of your fork?

**Comment by rwdudley-usgs** [comment]
Hmmm. I can't recreate it now. Just now I went back to my fork and made a pull request and it was all there. I must have been doing something dumb somewhere.
Seems like when I pressed the button for pull request earlier, all I got were a couple unpopulated drop downs. Maybe it was the USGS-R organization?

**Comment by ldecicco-USGS** [comment]
That would be my guess

**Comment by grrmartin-USGS** [comment]
Now my PC fork matches the latest wateRuse.Rmd, after git pulling into new
project.  So now I'll update my PC fork copy and send a pull request.
